[package]
name = "falling_pixels"
version = "0.1.0"
authors = ["jacob"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14.1"
